from numpy.f2py.auxfuncs import throw_error
try:
    a="S"
    print(ord(a))
except Exception:
    print(str(Exception))